# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2017
  project: Anti-Robots
  version: 0.1
  release: 0.1.0
  latex_documents:
  - - Index
    - news_anti_robots.tex
    - Anti-Robots
    - Markus Kugler
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
